### ISSUE TITLE
More chat utterances and answers

### ISSUE THREAD

**Issue by francocontigo** [CaravanaCloud/blink#19]
Create new utterances for the chatbot such as:

- What precautions should I take before and after donation?
- Do I need to fast before donating blood?
- Can I drink before/after donating blood?
- I have tattoos, can I donate?
- I had unprotected sex recently, can I donate blood?
- I am taking medication Xxxxxxxx, can I donate? (Study feasibility)

And consider existing social paradigms, such as:
- I had homosexual relations recently, can I donate blood?

**Comment by francocontigo** [comment]
@GarvAgarwal26 yeah, i was working on some responses and this is the pull request i've made https://github.com/CaravanaCloud/blink/pull/20 , we can work together!

**Comment by GarvAgarwal26** [comment]
It will be great to work with you...Pls mention if you have done any prior work on this

**Comment by francocontigo** [comment]
I've worked a bit on these questions:

What precautions should I take before and after donation? (precautions_before_after.txt)
Do I need to fast before donating blood? (need_to_fast.txt)
Can I drink before/after donating blood? (drink_before_after.txt)
I have tattoos, can I donate? (have_tattoos.txt)
I had unprotected sex recently, can I donate blood? (unprotected_relation.txt)

Think we can summarize the answers for precautions more concisely, and need to review the tone for the last one.
Searching about drinking alcoholic beverages before donation, there's the alcohol content in grams vs required time to wait for donation, maybe better way to communicate?

**Comment by GarvAgarwal26** [comment]
I had unprotected sex recently, can I donate blood?

If you've had recent unprotected sex, it's best to wait before donating. If your last year involved a stable, monogamous relationship without condoms, you should be eligible. For any uncertainties, check with your local blood center. Thanks for considering!

Is the tone of the answer now okay Sir??

**Comment by GarvAgarwal26** [comment]
Sir, can I mention in the request changes or do I also have to make the pull request for this?

**Comment by francocontigo** [comment]
I think you can pull request for this in this issue work branch

**Comment by GarvAgarwal26** [comment]
Ok sir , So now moving to the next i will help you out in alcoholic drinks part

**Comment by GarvAgarwal26** [comment]
Sir, will you please check #21 is it okay or have I made some mistake in creating the pull request??

**Comment by francocontigo** [comment]
No problem, i'll wait for someone else to review our pull requests

**Comment by GarvAgarwal26** [comment]
Hey I want to ask you how to add a request a review from the maintainers...can u please help me out as I am new to the open-source
